FROM php:8.3-cli

# Install dependencies dasar + ekstensi yang dibutuhkan Laravel & Filament
RUN apt-get update && apt-get install -y \
    git unzip libzip-dev libicu-dev libonig-dev libxml2-dev zlib1g-dev \
    && docker-php-ext-install intl zip pdo pdo_mysql

# Install Composer
COPY --from=composer:2.7 /usr/bin/composer /usr/bin/composer

# Set working directory
WORKDIR /app

# Copy composer files terlebih dahulu untuk cache layer
COPY composer.json composer.lock ./

# Install dependency Laravel (sebelum copy semua file, agar cache lebih efisien)
RUN composer install --optimize-autoloader --no-dev

# Copy semua file project
COPY . .

# Generate cache
RUN php artisan config:cache \
    && php artisan route:cache \
    && php artisan view:cache

# Jalankan Laravel
CMD php artisan serve --host=0.0.0.0 --port=$PORT

RUN php -m && php --ri intl && php --ri zip