# Gunakan image resmi PHP 8.2 dengan Composer
FROM php:8.2-cli

# Install dependencies dasar + ekstensi yang dibutuhkan Laravel & Filament
RUN apt-get update && apt-get install -y \
    git unzip libzip-dev libicu-dev libonig-dev libxml2-dev \
    && docker-php-ext-install pdo pdo_mysql intl zip

# Install Composer
COPY --from=composer:2.7 /usr/bin/composer /usr/bin/composer

# Set working directory
WORKDIR /app

# Copy semua file project
COPY . .

# Install dependency Laravel
RUN composer install --optimize-autoloader --no-dev

# Generate cache
RUN php artisan config:cache \
    && php artisan route:cache \
    && php artisan view:cache

# Jalankan Laravel
CMD php artisan serve --host=0.0.0.0 --port=$PORT
