name: Deploy Laravel + Filament to Railway

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          extensions: mbstring, bcmath, mysqli, pdo, pdo_mysql, zip, gd, intl

      - name: Install Composer dependencies
        run: composer install --no-dev --prefer-dist --optimize-autoloader

      - name: Generate Laravel app key
        run: php artisan key:generate --ansi

      - name: Create storage link
        run: php artisan storage:link

      - name: Cache config and routes
        run: |
          php artisan config:cache
          php artisan route:cache

      - name: Run migrations
        env:
          DB_CONNECTION: ${{ secrets.DB_CONNECTION }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_DATABASE: ${{ secrets.DB_DATABASE }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: php artisan migrate --force

      - name: Deploy
        run: echo "Railway will automatically deploy this commit"
